
#
#
# https://jekyllrb.com/docs/configuration/
#
#
url: https://starterkitmedia.com
baseurl: ''

# Custom vars
#google_analytics: UA-

#
# Meta tags and User-facing descriptions
#
title: StarterKit Media - Studio-quality media assets, Los Angeles and Kauai.
email: connect@starterkitmedia.com
description: "Studio-quality media assets for emerging artists and businesses. Professional facilities on the island of Kauai and in Los Angeles. Contact us today for a quote!"

# Blog-related
show_excerpts: true

# Directory / Files - what does this do?
# defaults:
#   - scope:
#       path: "assets/img"
#     values:
#       image: true

# Team names, titles and social links
people:
- name: Paul Cline
  image: paul-cline-aka-brother-peace-cee
  position: Executive Producer
  bio: Avid and Final Cut Pro-certified.
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/paul-cline-a5a10457/
    - title: facebook
      url: https://www.facebook.com/unknownendeavors/

- name: Brandon Zeolla
  image: brandon-zeolla
  position: Video Production
  bio:
  social:
    - title: instagram
      url: https://www.instagram.com/mr_doctor_z
    - title: facebook
      url: https://www.facebook.com/brandon.zeolla

- name: Brent Boberg
  image: brent-boberg
  position: Mixer, Songwriter
  bio:
  social:
    - title: instagram
      url: https://www.instagram.com/brentboberg/
    - title: facebook
      url: https://www.facebook.com/brent.boberg

- name: Raku Media
  image: raku-media
  position: Media Production
  bio:
  social:
    - title: twitter
      url: https://twitter.com/RakuMediaLLC
    - title: facebook
      url: https://www.facebook.com/RakuMedia

# Social network handles
# (eg: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/unknown_endeavors/
  - title: vimeo
    url: https://vimeo.com/unknownendeavors
  - title: twitter
    url: https://twitter.com/unknownendvrs
  - title: facebook
    url: https://www.facebook.com/pg/unknownendeavors/


# Postal address (add as many lines as necessary)
address:
#  - line: Los Angeles, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
