#
#
# https://jekyllrb.com/docs/configuration/
#
#
url: https://starterkitmedia.com
baseurl: ''

# Custom vars
#google_analytics: UA-

#
# Meta tags and User-facing descriptions
#
title: StarterKit Media - Studio-quality video production, demo track recording and media assets in Los Angeles and Kauai.
abridged: StarterKit Media - Studio-quality video and audio production. Los Angeles + Kauai.
email: hello@starterkitmedia.com
description: "Studio-quality video production, demo track recording, and media assets for emerging artists and businesses. Professional facilities on the island of Kauai and in Los Angeles."

# Blog-related
show_excerpts: true

# Site-levelw network handles
# (eg: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/starterkitmedia/
  - title: flickr
    url: https://www.flickr.com/photos/starterkitmedia/
  #- title: vimeo
  #  url: https://vimeo.com/unknownendeavors
  - title: youtube
    url: https://www.youtube.com/channel/UC5SzlcR3h2gW9bl7tqX2Gzg
  - title: facebook
    url: http://fb.me/starterkitmedia

# Create team member pages from src/_team/*.md files
collections:
  team:
    output: true
  clients:
    output: true
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# # Postal address (add as many lines as necessary)
# address:
# #  - line: Los Angeles, CA 90210


# Directory / Files - what does this do?
# defaults:
#   - scope:
#       path: "assets/img"
#     values:
#       image: true




