#
#
# https://jekyllrb.com/docs/configuration/
#
#
url: https://starterkitmedia.com
baseurl: ''

# Custom vars
#google_analytics: UA-

#
# Meta tags and User-facing descriptions
#
title: StarterKit Media - Studio-quality media assets, Los Angeles and Kauai.
email: connect@starterkitmedia.com
description: "Studio-quality media assets for emerging artists and businesses. Professional facilities on the island of Kauai and in Los Angeles. Contact us today for a quote!"

# Blog-related
show_excerpts: true

# Site-levelw network handles
# (eg: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/unknown_endeavors/
  - title: vimeo
    url: https://vimeo.com/unknownendeavors
  - title: twitter
    url: https://twitter.com/unknownendvrs
  - title: facebook
    url: https://www.facebook.com/pg/unknownendeavors/

# Create team member pages from src/_team/*.md files
collections:
  team:
    output: true
  clients:
    output: true
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# # Postal address (add as many lines as necessary)
# address:
# #  - line: Los Angeles, CA 90210


# Directory / Files - what does this do?
# defaults:
#   - scope:
#       path: "assets/img"
#     values:
#       image: true




